// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_DtJFzWm3SMy-NkT0btXouP2V8nTT-PE',
    appId: '1:57512780409:web:160f174ac978846c23aaa8',
    messagingSenderId: '57512780409',
    projectId: 'shopapp-3ab85',
    authDomain: 'shopapp-3ab85.firebaseapp.com',
    databaseURL: 'https://shopapp-3ab85-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-3ab85.appspot.com',
    measurementId: 'G-GDPCWW3V0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv5HjqIjI97HebN4KkgBYFCmmP6pQayGE',
    appId: '1:57512780409:android:195e12c00459532323aaa8',
    messagingSenderId: '57512780409',
    projectId: 'shopapp-3ab85',
    databaseURL: 'https://shopapp-3ab85-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-3ab85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRWHQw-5aV7gChESq35xNlI3rMJ6k2jKs',
    appId: '1:57512780409:ios:cb2a70a1b7dc021f23aaa8',
    messagingSenderId: '57512780409',
    projectId: 'shopapp-3ab85',
    databaseURL: 'https://shopapp-3ab85-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-3ab85.appspot.com',
    androidClientId: '57512780409-obhl7d1p8jgsbptvags0131u4kknfsma.apps.googleusercontent.com',
    iosClientId: '57512780409-abvh4dmpfmjnp44eak8dv57j947hohac.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryappdeliverit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRWHQw-5aV7gChESq35xNlI3rMJ6k2jKs',
    appId: '1:57512780409:ios:cb2a70a1b7dc021f23aaa8',
    messagingSenderId: '57512780409',
    projectId: 'shopapp-3ab85',
    databaseURL: 'https://shopapp-3ab85-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-3ab85.appspot.com',
    androidClientId: '57512780409-obhl7d1p8jgsbptvags0131u4kknfsma.apps.googleusercontent.com',
    iosClientId: '57512780409-abvh4dmpfmjnp44eak8dv57j947hohac.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryappdeliverit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYZWpChcJ-yDUl38w3IfvUPZjY0usMUvE',
    appId: '1:57512780409:web:797b5b2b4a2ebe2a23aaa8',
    messagingSenderId: '57512780409',
    projectId: 'shopapp-3ab85',
    authDomain: 'shopapp-3ab85.firebaseapp.com',
    databaseURL: 'https://shopapp-3ab85-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-3ab85.appspot.com',
    measurementId: 'G-NXJY7X4BDN',
  );

}